package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);
    Cart selectCartByUseridAndProduct(@Param("userId") Integer userId,
                                      @Param("productId")Integer productId);

    /**
     * 查询用户的购物车信息
     * @param userId
     * @return
     */
    List<Cart> selectCartByUserid(@Param("userId") Integer userId);
    /**
     * 统计用户购物信息是否全选
     * 返回值>0，未全选
     */
    int isCheckedAll(Integer userId);
    /**
     * 删除购物车某些商品
     */
    int deleteByUseridAndProductIds(@Param("userId")Integer userId,@Param("productIdList")List<Integer> productIdList);
    /**
     * 操作购物车商品是否选中
     * check=1,选中
     */
    int selectOrUnselectProduct(@Param("userId")Integer userId,@Param("productId")Integer productId,
                                @Param("check")Integer check);

    int get_cart_product_count(Integer userId);
    /**
     * 查询购物车中已选中的商品
     */
   List<Cart> findCartByUserIdAndChecked(Integer userId);
    /**
     * 批量删除购物车商品
     */
   int batchDelete(List<Cart> cartList);

}